### ISSUE TITLE
Get Backend hosted with public APIs

### ISSUE THREAD

**Issue by Esauidk** [ngutn24/RollBuddy#61]

**Comment by leftl** [comment]
Just for visibility: frontend changes needed to adopt this will be on the branch [frontend_hosted_API](github.com/ngutn24/RollBuddy/tree/frontend_hosted_API).
Let me know when you have a pull request up. For other frontend people, this will require adding a new character ID to every API request (that is independent of the spark session id). On character creation, we will store this ID in local storage and pass it as a url parameter with request.
