### ISSUE TITLE
Cannot Run backend with given command. Build failure

### ISSUE THREAD

**Issue by michael7291** [ngutn24/RollBuddy#85]
**Describe the bug**
Unable to successfully run the backend with `./gradlew run_backend` 

**To Reproduce**
1. cd into RollBuddy
2. run `./gradlew run_backend` 

**Expected behavior**

Expected the backend to show message that indicates succesful build

**Screenshots**

<img width="896" alt="image" src="https://user-images.githubusercontent.com/35711500/169746313-8ba0655e-ad6b-4f00-8a04-78c9e3225c55.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Esauidk** [comment]
Did you make sure to correctly setup java on your system?

**Comment by leftl** [comment]
Hi Michael, thanks for your bug report. I believe this is an issue with environment variables, if you can share the output of `echo %JAVA_HOME%` (via Command Prompt) or `Get-ChildItem Env:JAVA_HOME` (via PowerShell) with us we can try to help!

Alternatively, you can use app directly by visiting https://ngutn24.github.io/RollBuddy

**Comment by michael7291** [comment]
@leftl  @Esauidk  Hey guys, here's what I get when I run `Get-ChildItem Env:JAVA_HOME` 

<img width="607" alt="image" src="https://user-images.githubusercontent.com/35711500/169890093-5d9ebf0b-2dcc-4fc1-b172-6b9dd0b0967e.png">

**Comment by leftl** [comment]
Thank you for the response, it's definitely an environment variable issue. If you follow the instructions [here](https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html) it will help you update this variable (you may have to run `where java` to find the destination of your JDK installation).
I will update the installation portion of our user guide if this is not automatically set by the installer, thanks again for pointing this out. 
I do suggest that you review our app via the hosted version here: [https://ngutn24.github.io/RollBuddy](https://ngutn24.github.io/RollBuddy) as opposed to hosting it yourself.

**Comment by michael7291** [comment]
@leftl awesome. Thanks!
