### ISSUE TITLE
Build steps in README don't include building front end

### ISSUE THREAD

**Issue by Avekeez** [ngutn24/RollBuddy#86]
**Describe the bug**
Following the README and running `./gradlew npm_start` on a clean repository results in a build error, as a task running `npm install` was not previously called.

**To Reproduce**
1. Clone the repository as specified in the README
2. Open the project in Intellij 2022
3. Run `./gradlew npm_start`
4. See build error

**Expected behavior**
The frontend project should be started as stated in the README.

**Desktop (please complete the following information):**
- JVM: 11.0.9.1 (AdoptOpenJDK 11.0.9.1+1)
- OS: Windows 10 10.0 amd64
- Gradle: 7.1.1

**Comment by leftl** [comment]
Thanks for the bug report, this has been fixed! We have made a new task which will prevent this issue, `run_frontend`, and this has been reflected in the user manual. 

Alternatively, you can now use our app by simply visiting https://ngutn24.github.io/RollBuddy/ 👍
